# Generated by Django 4.2.25 on 2025-10-29 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreinamentoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados_sst/')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treinamentos_ministrados', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(related_name='treinamentos_sst', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Treinamento SST',
                'verbose_name_plural': 'Treinamentos SST',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='PerigoRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=200)),
                ('perigo', models.CharField(help_text='Ex: Queda, choque elétrico, ruído, produto químico', max_length=200)),
                ('risco', models.CharField(help_text='Ex: Fratura, queimadura, perda auditiva', max_length=200)),
                ('nivel_risco', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20)),
                ('medidas_controle', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('identificado', 'Identificado'), ('controlado', 'Controlado'), ('eliminado', 'Eliminado')], default='identificado', max_length=20)),
                ('data_identificacao', models.DateField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perigo e Risco',
                'verbose_name_plural': 'Perigos e Riscos',
                'ordering': ['-data_identificacao'],
            },
        ),
        migrations.CreateModel(
            name='Acidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acidente', 'Acidente'), ('incidente', 'Incidente sem lesão')], default='acidente', max_length=20)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('causa_raiz', models.TextField(blank=True)),
                ('medidas_corretivas', models.TextField(blank=True)),
                ('evidencias', models.FileField(blank=True, null=True, upload_to='acidentes/')),
                ('testemunhas', models.ManyToManyField(blank=True, related_name='testemunhas', to=settings.AUTH_USER_MODEL)),
                ('vitima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vitima', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acidente / Incidente',
                'verbose_name_plural': 'Acidentes e Incidentes',
                'ordering': ['-data'],
            },
        ),
    ]
