# Generated by Django 4.2.25 on 2025-10-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('eficacia', 'Eficácia'), ('eficiencia', 'Eficiência'), ('qualidade', 'Qualidade'), ('satisfacao', 'Satisfação')], max_length=20)),
                ('formula_calculo', models.TextField()),
                ('meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_medida', models.CharField(max_length=50)),
                ('frequencia_medicao', models.CharField(max_length=50)),
                ('responsavel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicaoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_medicao', models.DateField()),
                ('valor_medio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.indicador')),
            ],
        ),
    ]
