# Generated by Django 4.2.25 on 2025-10-31 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicadores', '0002_indicador_categoria_indicador_norma'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIndicador',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('norma', models.CharField(choices=[('iso9001', 'ISO 9001 - Qualidade'), ('iso14001', 'ISO 14001 - Meio Ambiente'), ('iso45001', 'ISO 45001 - Saúde e Segurança Ocupacional'), ('integrado', 'Integrado (SGI)')], default='iso9001', max_length=20)),
                ('categoria', models.CharField(choices=[('qualidade', 'Qualidade'), ('ambiental', 'Ambiental'), ('sst', 'Saúde e Segurança')], default='qualidade', max_length=20)),
                ('tipo', models.CharField(choices=[('eficacia', 'Eficácia'), ('eficiencia', 'Eficiência'), ('qualidade', 'Qualidade'), ('satisfacao', 'Satisfação')], max_length=20)),
                ('formula_calculo', models.TextField()),
                ('meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_medida', models.CharField(max_length=50)),
                ('frequencia_medicao', models.CharField(max_length=50)),
                ('responsavel', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicadores.indicador')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical indicador',
                'verbose_name_plural': 'historical indicadors',
                'db_table': 'indicadores_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
