# Generated by Django 4.2.25 on 2025-10-29 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicencaAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('orgao_emissor', models.CharField(max_length=150)),
                ('validade', models.DateField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='licencas_ambientais/')),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Licença Ambiental',
                'verbose_name_plural': 'Licenças Ambientais',
            },
        ),
        migrations.CreateModel(
            name='EmergenciaAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(help_text='Ex: Vazamento de óleo, incêndio', max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('medidas_adotadas', models.TextField()),
                ('evidencias', models.FileField(blank=True, null=True, upload_to='emergencias_ambientais/')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergência Ambiental',
                'verbose_name_plural': 'Emergências Ambientais',
            },
        ),
        migrations.CreateModel(
            name='AspectoImpactoAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(help_text='Processo ou atividade analisada', max_length=200)),
                ('aspecto', models.CharField(help_text='Ex: Consumo de energia, emissão de gases', max_length=200)),
                ('impacto', models.CharField(help_text='Ex: Poluição atmosférica, uso de recursos naturais', max_length=200)),
                ('nivel_significancia', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20)),
                ('medidas_controle', models.TextField(blank=True, help_text='Controles existentes ou planejados')),
                ('legislacao_aplicavel', models.TextField(blank=True, help_text='Legislação e requisitos aplicáveis')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('controlado', 'Controlado'), ('eliminado', 'Eliminado')], default='ativo', max_length=20)),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aspecto e Impacto Ambiental',
                'verbose_name_plural': 'Aspectos e Impactos Ambientais',
                'ordering': ['-data_avaliacao'],
            },
        ),
    ]
