# Generated by Django 4.2.25 on 2025-10-31 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meio_ambiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLicencaAmbiental',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=50)),
                ('orgao_emissor', models.CharField(max_length=150)),
                ('validade', models.DateField()),
                ('arquivo', models.TextField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='meio_ambiente.licencaambiental')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Licença Ambiental',
                'verbose_name_plural': 'historical Licenças Ambientais',
                'db_table': 'licenca_ambiental_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEmergenciaAmbiental',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_evento', models.CharField(help_text='Ex: Vazamento de óleo, incêndio', max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('medidas_adotadas', models.TextField()),
                ('evidencias', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='meio_ambiente.emergenciaambiental')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Emergência Ambiental',
                'verbose_name_plural': 'historical Emergências Ambientais',
                'db_table': 'emergencia_ambiental_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAspectoImpactoAmbiental',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('processo', models.CharField(help_text='Processo ou atividade analisada', max_length=200)),
                ('aspecto', models.CharField(help_text='Ex: Consumo de energia, emissão de gases', max_length=200)),
                ('impacto', models.CharField(help_text='Ex: Poluição atmosférica, uso de recursos naturais', max_length=200)),
                ('nivel_significancia', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20)),
                ('medidas_controle', models.TextField(blank=True, help_text='Controles existentes ou planejados')),
                ('legislacao_aplicavel', models.TextField(blank=True, help_text='Legislação e requisitos aplicáveis')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('controlado', 'Controlado'), ('eliminado', 'Eliminado')], default='ativo', max_length=20)),
                ('data_avaliacao', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='meio_ambiente.aspectoimpactoambiental')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Aspecto e Impacto Ambiental',
                'verbose_name_plural': 'historical Aspectos e Impactos Ambientais',
                'db_table': 'impacto_ambiental_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
