# Generated by Django 4.2.25 on 2025-10-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15, unique=True)),
                ('data_planejada', models.DateField()),
                ('data_realizada', models.DateField(blank=True, null=True)),
                ('setor_auditado', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('executada', 'Em Execução'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejada', max_length=20)),
                ('relatorio', models.FileField(blank=True, upload_to='relatorios_auditoria/')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
            },
        ),
        migrations.CreateModel(
            name='ProgramaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('objetivo', models.TextField()),
                ('escopo', models.TextField()),
                ('criterios', models.TextField()),
            ],
        ),
    ]
