# Generated by Django 4.2.25 on 2025-10-28 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='auditores',
            field=models.ManyToManyField(related_name='auditorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_lideradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auditorias.programaauditoria'),
        ),
    ]
