# Generated by Django 4.2.25 on 2025-10-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='norma',
            field=models.CharField(choices=[('iso9001', 'ISO 9001 - Qualidade'), ('iso14001', 'ISO 14001 - Meio Ambiente'), ('iso45001', 'ISO 45001 - Saúde e Segurança Ocupacional'), ('integrado', 'Integrado (SGI)')], default='iso9001', max_length=20),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='tipo',
            field=models.CharField(choices=[('qualidade', 'Qualidade (ISO 9001)'), ('ambiental', 'Meio Ambiente (ISO 14001)'), ('sst', 'Saúde e Segurança (ISO 45001)'), ('integrada', 'Integrada (SGI)')], default='qualidade', max_length=20),
        ),
    ]
