# Generated by Django 4.2.25 on 2025-10-31 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditorias', '0003_auditoria_norma_auditoria_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProgramaAuditoria',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('objetivo', models.TextField()),
                ('escopo', models.TextField()),
                ('criterios', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auditorias.programaauditoria')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical programa auditoria',
                'verbose_name_plural': 'historical programa auditorias',
                'db_table': 'progrma_auditoria_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAuditoria',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=15)),
                ('norma', models.CharField(choices=[('iso9001', 'ISO 9001 - Qualidade'), ('iso14001', 'ISO 14001 - Meio Ambiente'), ('iso45001', 'ISO 45001 - Saúde e Segurança Ocupacional'), ('integrado', 'Integrado (SGI)')], default='iso9001', max_length=20)),
                ('tipo', models.CharField(choices=[('qualidade', 'Qualidade (ISO 9001)'), ('ambiental', 'Meio Ambiente (ISO 14001)'), ('sst', 'Saúde e Segurança (ISO 45001)'), ('integrada', 'Integrada (SGI)')], default='qualidade', max_length=20)),
                ('data_planejada', models.DateField()),
                ('data_realizada', models.DateField(blank=True, null=True)),
                ('setor_auditado', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('executada', 'Em Execução'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejada', max_length=20)),
                ('relatorio', models.TextField(blank=True, max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auditorias.auditoria')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auditorias.programaauditoria')),
            ],
            options={
                'verbose_name': 'historical Auditoria',
                'verbose_name_plural': 'historical Auditorias',
                'db_table': 'auditoria_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
