# Generated by Django 4.2.25 on 2025-10-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('revisao', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('revisao', 'Em Revisão'), ('aprovado', 'Aprovado'), ('obsoleto', 'Obsoleto')], default='rascunho', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('data_elaboracao', models.DateField(auto_now_add=True)),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('controle_alteracoes', models.TextField(blank=True, help_text='Registro de alterações entre revisões')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_elaboracao'],
            },
        ),
    ]
