# Generated by Django 4.2.25 on 2025-10-28 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao_documental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='aprovador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_documental.categoriadocumento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='elaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_elaborados', to=settings.AUTH_USER_MODEL),
        ),
    ]
