# Generated by Django 4.2.25 on 2025-10-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_documental', '0003_documento_norma_documento_tipo_norma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='tipo_norma',
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('PO', 'Política'), ('MQ', 'Manual'), ('PR', 'Procedimento'), ('IT', 'Instrução de Trabalho'), ('POP', 'Procedimento Operacional Padrão'), ('FM', 'Formulário'), ('RG', 'Registro'), ('OT', 'Outro')], default='PR', max_length=5),
        ),
        migrations.AddField(
            model_name='documento',
            name='versao_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_documental.documento'),
        ),
    ]
