# Generated by Django 4.2.25 on 2025-10-31 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao_documental', '0004_remove_documento_tipo_norma_documento_tipo_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDocumento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('tipo_documento', models.CharField(choices=[('PO', 'Política'), ('MQ', 'Manual'), ('PR', 'Procedimento'), ('IT', 'Instrução de Trabalho'), ('POP', 'Procedimento Operacional Padrão'), ('FM', 'Formulário'), ('RG', 'Registro'), ('OT', 'Outro')], default='PR', max_length=5)),
                ('norma', models.CharField(choices=[('iso9001', 'ISO 9001 - Qualidade'), ('iso14001', 'ISO 14001 - Meio Ambiente'), ('iso45001', 'ISO 45001 - Saúde e Segurança Ocupacional'), ('integrado', 'Integrado (SGI)')], default='iso9001', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('revisao', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('revisao', 'Em Revisão'), ('aprovado', 'Aprovado'), ('obsoleto', 'Obsoleto')], default='rascunho', max_length=20)),
                ('arquivo', models.TextField(blank=True, max_length=100, null=True)),
                ('data_elaboracao', models.DateField(blank=True, editable=False)),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('controle_alteracoes', models.TextField(blank=True, help_text='Registro de alterações entre revisões')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aprovador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao_documental.categoriadocumento')),
                ('elaborador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao_documental.documento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('versao_anterior', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao_documental.documento')),
            ],
            options={
                'verbose_name': 'historical Documento',
                'verbose_name_plural': 'historical Documentos',
                'db_table': 'gestao_documental_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
