# Generated by Django 4.2.25 on 2025-10-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('setor_envolvido', models.CharField(max_length=100)),
                ('data_deteccao', models.DateField()),
                ('data_limite', models.DateField()),
                ('gravidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='aberta', max_length=20)),
                ('causa_raiz', models.TextField(blank=True)),
                ('acao_corretiva', models.TextField(blank=True)),
                ('data_implementacao', models.DateField(blank=True, null=True)),
                ('eficaz', models.BooleanField(blank=True, null=True)),
                ('evidencias', models.FileField(blank=True, null=True, upload_to='evidencias_nc/')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Não Conformidade',
                'verbose_name_plural': 'Não Conformidades',
                'ordering': ['-data_deteccao'],
            },
        ),
    ]
