# Generated by Django 4.2.25 on 2025-10-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nao_conformidades', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naoconformidade',
            name='norma',
            field=models.CharField(choices=[('iso9001', 'ISO 9001 - Qualidade'), ('iso14001', 'ISO 14001 - Meio Ambiente'), ('iso45001', 'ISO 45001 - Saúde e Segurança Ocupacional'), ('integrado', 'Integrado (SGI)')], default='iso9001', max_length=20),
        ),
    ]
