# Generated by Django 4.2.25 on 2025-10-28 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseCritica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Ex: 1º Trimestre 2024', max_length=50)),
                ('data_reuniao', models.DateField()),
                ('data_proxima_reuniao', models.DateField()),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='planejada', max_length=20)),
                ('kpis_analisados', models.TextField(blank=True, help_text='Indicadores analisados (um por linha)', null=True)),
                ('ncs_analisadas', models.TextField(blank=True, help_text='Não conformidades analisadas (uma por linha)', null=True)),
                ('auditorias_analisadas', models.TextField(blank=True, help_text='Auditorias analisadas (uma por linha)', null=True)),
                ('recursos_necessarios', models.TextField(blank=True, help_text='Recursos necessários identificados (um por linha)', null=True)),
                ('decisoes_tomadas', models.TextField()),
                ('acoes_melhoria', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('ata_reuniao', models.FileField(blank=True, upload_to='atas_analise_critica/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_coordenadas', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(related_name='analises_criticas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análise Crítica',
                'verbose_name_plural': 'Análises Críticas',
                'ordering': ['-data_reuniao'],
            },
        ),
    ]
