# Generated by Django 4.2.25 on 2025-10-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_critica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecritica',
            name='norma',
            field=models.CharField(choices=[('iso9001', 'ISO 9001 - Qualidade'), ('iso14001', 'ISO 14001 - Meio Ambiente'), ('iso45001', 'ISO 45001 - Saúde e Segurança Ocupacional'), ('integrado', 'Integrado (SGI)')], default='iso9001', max_length=20),
        ),
        migrations.AddField(
            model_name='analisecritica',
            name='temas_ambientais',
            field=models.TextField(blank=True, help_text='Aspectos e impactos ambientais discutidos'),
        ),
        migrations.AddField(
            model_name='analisecritica',
            name='temas_sst',
            field=models.TextField(blank=True, help_text='Riscos e oportunidades de SST abordados'),
        ),
    ]
