# Generated by Django 4.2.25 on 2025-10-31 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analise_critica', '0002_analisecritica_norma_analisecritica_temas_ambientais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAnaliseCritica',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Ex: 1º Trimestre 2024', max_length=50)),
                ('norma', models.CharField(choices=[('iso9001', 'ISO 9001 - Qualidade'), ('iso14001', 'ISO 14001 - Meio Ambiente'), ('iso45001', 'ISO 45001 - Saúde e Segurança Ocupacional'), ('integrado', 'Integrado (SGI)')], default='iso9001', max_length=20)),
                ('data_reuniao', models.DateField()),
                ('data_proxima_reuniao', models.DateField()),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='planejada', max_length=20)),
                ('kpis_analisados', models.TextField(blank=True, help_text='Indicadores analisados (um por linha)', null=True)),
                ('ncs_analisadas', models.TextField(blank=True, help_text='Não conformidades analisadas (uma por linha)', null=True)),
                ('auditorias_analisadas', models.TextField(blank=True, help_text='Auditorias analisadas (uma por linha)', null=True)),
                ('recursos_necessarios', models.TextField(blank=True, help_text='Recursos necessários identificados (um por linha)', null=True)),
                ('decisoes_tomadas', models.TextField()),
                ('acoes_melhoria', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('ata_reuniao', models.TextField(blank=True, max_length=100)),
                ('temas_ambientais', models.TextField(blank=True, help_text='Aspectos e impactos ambientais discutidos')),
                ('temas_sst', models.TextField(blank=True, help_text='Riscos e oportunidades de SST abordados')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('coordenador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='analise_critica.analisecritica')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Análise Crítica',
                'verbose_name_plural': 'historical Análises Críticas',
                'db_table': 'analise_critica_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
